version: '3'

services:
  postgres: 
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redis_db_poc
    volumes:
      - .:/app
    ports: 
      - "5432:5432"
    restart: always

  redis:
    image: redis
    hostname: redis
    container_name: redis
    environment:
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379
      REDIS_DATABASES: 0
    ports:
      - "6379:6379" 
    restart: always

  redis_poc:
    build: 
      context: .
    container_name: redis-poc
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - redis
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
  
  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    command: ["-path", "app/migrations/", "-database",  "postgres://postgres:postgres@postgres:5432/redis_db_poc?sslmode=disable", "up"]
    depends_on:
      - postgres
    restart: on-failure