version: '3'

services:
  postgres: 
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redis_db_poc
    volumes:
      - postgresdata:/home/server/db/data
    ports: 
      - "5432:5432"
    networks:
      - redispocnetwork
    restart: always

  redis_poc:
    build: 
      context: .
    container_name: redis-poc
    volumes:
      - .:/home/server/
    ports:
      - "8085:8085"
    networks:
      - redispocnetwork
    depends_on:
      - postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - redispocnetwork
    depends_on:
      - postgres
    restart: always

volumes:
  postgresdata:

networks:
  redispocnetwork: